# Generated by Django 5.2.17 on 2026-08-23 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_customerprofile_saved_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['session_key', 'phone_e164', '-created_at'], name='webchat_pho_session_70a939_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('in', 'From visitor'), ('out', 'From platform')], max_length=3)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('location', 'Location shared'), ('image', 'Image uploaded'), ('system', 'System')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['phone_e164', 'id'], name='webchat_web_phone_e_aef6fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webchat_sessions', to='accounts.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'last_seen_at'], name='webchat_web_user_id_303fda_idx')],
            },
        ),
    ]
