# Generated by Django 5.2.17 on 2026-08-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_received', to='accounts.user')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='bookings.booking')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_given', to='accounts.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
