# Generated by Django 5.2.17 on 2026-08-17 19:54

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='offer_code',
            field=models.CharField(db_index=True, default=marketplace.models.generate_offer_code, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='match',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='response_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
