# Generated by Django 5.2.17 on 2026-08-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_artisanprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
