# Generated by Django 5.2.17 on 2026-08-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
