# Generated by Django 5.2.17 on 2026-08-17 19:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_artisanprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='saved_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
