# Generated by Django 5.2.17 on 2026-08-11 02:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('job_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(db_index=True, max_length=30, unique=True)),
                ('agreed_amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('in_progress', 'In Progress'), ('artisan_completed', 'Artisan Marked Complete'), ('customer_completed', 'Customer Confirmed Complete'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=30)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_artisan', to='accounts.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_customer', to='accounts.user')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='job_requests.servicerequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
            ],
            options={
                'verbose_name_plural': 'booking status histories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReliabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('late_cancel_customer', 'Customer Cancelled Late'), ('late_cancel_artisan', 'Artisan Cancelled Late'), ('no_show_customer', 'Customer No-Show'), ('no_show_artisan', 'Artisan No-Show')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_events', to='bookings.booking')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
