# Generated by Django 5.2.17 on 2026-08-16 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
