# Generated by Django 5.2.17 on 2026-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('webchat', 'Web Chat'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=10),
        ),
    ]
